### ISSUE TITLE
0425 TODO 

### ISSUE THREAD

**Issue by jjimini98** [Project-gongbooisselfstudy/selfStudy_backend#1]
**Question**

- [ ] question/load  : randomList가 끝나면 새로 또 랜덤으로 리스트 만들어서 계속 문제를 보여줘야한다.
- [ ] question/load : id 별로 나눠서 랜덤 리스트를 생성해야함 : 현재는 id 모두 섞어서 랜덤 리스트를 생성하는 중

**Wrong**

- [x] wrong_id : DB에 insert 될 때 번호가 2부터 시작함. 1번부터 시작되도록 바꿔야함 -> ++count 때문이었음 
- [x] JDBCWrongRepository : randomList 값이 이상하게 들어감 왠지 id  와 연관된 문제 같음

**ETC**

- [ ] travis 빌드 성공 후 메일이 안옴;
